#pragma once

// Binance Futures Testnet broker: real signed REST against
// testnet.binancefuture.com with simulated funds. This is the execution
// venue for paper trading — signals come from real production data, orders
// go here.
//
// Safety properties:
//   - Signed requests use HMAC-SHA256 + recvWindow=5000 + timestamp;
//     the server clock offset is checked at connect.
//   - 1x leverage, ISOLATED margin per symbol (notional ≈ margin, no
//     liquidation risk in paper).
//   - clientOrderId is generated by the engine and reused verbatim on
//     retry; this broker never resends an id it has seen acked.
//   - Exchange rejects are surfaced as errors; the engine logs them and
//     reconciles from positions on the next rebalance — never chase.

#include <map>
#include <set>
#include <string>
#include <vector>

#include "qse/live/broker.hpp"
#include "qse/live/http_client.hpp"   // HttpResponse

namespace qse::live {

class TestnetBroker final : public IBroker {
public:
    TestnetBroker(std::string api_key, std::string api_secret,
                  std::string base_url, int timeout_ms);

    bool connect(std::string& err) override;
    bool setup_symbols(const std::vector<std::string>& syms,
                       std::string& err) override;
    bool rules(const std::string& sym, SymbolRules& out) override;
    bool account(AccountInfo& out, std::string& err) override;
    bool positions(std::vector<PosRisk>& out, std::string& err) override;
    bool place(const std::vector<OrderSpec>& orders,
               std::vector<FillReport>& out, std::string& err) override;

private:
    // Signed GET/POST; params without the signature. Returns the response.
    // `err` is set on transport/HTTP failure. POST body carries the signed
    // query string (form-encoded), matching Binance's convention.
    bool signed_get(const std::string& path, const std::string& params,
                    HttpResponse& out, std::string& err);
    bool signed_post(const std::string& path, const std::string& params,
                     HttpResponse& out, std::string& err);

    bool fetch_exchange_info_(std::string& err);
    bool fetch_account_(AccountInfo& out, std::string& err);

    std::string api_key_, api_secret_, base_url_, host_;
    int timeout_ms_;
    std::map<std::string, SymbolRules> rules_;
    std::set<std::string> acked_ids_;
    std::set<std::string> bad_setup_;
};

}  // namespace qse::live
